### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [piyush97/khel-ke-baat-karen#2]
Hi @piyush97 , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by piyush97** [comment]
Sure. We'd love to see your talent!
@zularizal

**Comment by zularizal** [comment]
Okay, I need time to make it. And I will send it in the next reply.

**Comment by piyush97** [comment]
Sure!
